### Request to login route
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
    "username": "test",
    "password": "password"
}

### Request to register route
POST http://localhost:3000/api/v1/auth/register
Content-Type: application/json

{
    "username": "test",
    "password": "password",
    "displayName": "Test User",
    "email": "test@example.com"
}

### 
GET http://localhost:3000/api/v1/user/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2Mjc5MTM3NTIsImlkIjoiZTM0NzM5ODQtZmQ4YS00MjUzLWJlMDUtODFlZjVhMjNmMWRlIn0.YBzLEM2SKy2eX3zozo0m9L1NmND6yE659tV-uWXiEnE