### Request to login route
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
    "username": "test",
    "password": "password"
}

### Request to register route
POST http://localhost:3000/api/v1/auth/register
Content-Type: application/json

{
    "username": "test",
    "password": "password",
    "displayName": "Test User",
    "email": "test@example.com"
}

### 
DELETE http://localhost:3000/api/v1/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2Mjc5MjA5NDAsImlkIjoiOWM5NWMyNzUtNzQ0NS00ZmNhLTllNDktZTcxOTMxMWIxMmVhIn0.ve3M314DpJiIyoB66yST8BpnP0B7XjpDE8EbBCrRVi0

### Request to refresh token
POST http://localhost:3000/api/v1/auth/refresh
Content-Type: application/json

{
    "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijc4ZDNlOGQyLTk3MTUtNGE3MS04ZjZhLWRhNTA3MDg4NTA1NSJ9.ewCFymOmp8gy8DCUOHwZkY7T2hkCPNQV7BIEocnp6IM"
}

### Get the profile of the user with the provided token
GET http://localhost:3000/api/v1/user/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2Mjc5MjA5NDAsImlkIjoiOWM5NWMyNzUtNzQ0NS00ZmNhLTllNDktZTcxOTMxMWIxMmVhIn0.ve3M314DpJiIyoB66yST8BpnP0B7XjpDE8EbBCrRVi0